name: hello_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  go_router: 13.0.0
  flutter_svg: 2.0.0
  fluttertoast: 8.1.2
  flutter_dotenv: 5.1.0
  flutter_screenutil: 5.9.0
  http: 1.2.0 # For network call
  google_fonts: 6.1.0 # For custom fonts
  logger: 2.0.2 # For pretty print network logs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env/
    - assets/images/
